# fly.toml app configuration file generated for markitdown-floral-dawn-8574 on 2024-12-18T20:08:38-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markitdown-floral-dawn-8574'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
